### ISSUE TITLE
mix template.hex blowing up

### ISSUE THREAD

**Issue by MrTortoise** [pragdave/mix_generator#6]
installed the generator and templates ... then got this
```
Are you sure you want to install "mix_generator-0.1.9.ez"? [Yn] y
* creating /home/john/.mix/archives/mix_generator-0.1.9
john@John-Ubuntu:~/git$ mix template.hex
** (UndefinedFunctionError) function Hex.API.Package.search/1 is undefined or private. Did you mean one of:

      * search/2

    (hex) Hex.API.Package.search("gen_template")
    lib/mix/tasks/template.hex.ex:15: Mix.Tasks.Template.Hex.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2

```

**Comment by pragdave** [comment]
Asking the Hex team about this.

On Wed, Oct 4, 2017 at 10:56 AM, John Nicholas <notifications@github.com> wrote:
installed the generator and templates ... then got this

Are you sure you want to install "mix_generator-0.1.9.ez"? [Yn] y
* creating /home/john/.mix/archives/mix_generator-0.1.9
john@John-Ubuntu:~/git$ mix template.hex
** (UndefinedFunctionError) function Hex.API.Package.search/1 is undefined or private. Did you mean one of:

      * search/2

    (hex) Hex.API.Package.search("gen_template")
    lib/mix/tasks/template.hex.ex:15: Mix.Tasks.Template.Hex.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2

**Comment by pragdave** [comment]
So, they’ve changed a function I was calling in Hex.API.
I _think_ I have pushed a change that should work with both old and new hexes. Any chance you could try out master and see if it works for you?
Thanks

Dave

On Thu, Oct 5, 2017 at 5:33 PM, Dave Thomas <pragdave@gmail.com> wrote:
Asking the Hex team about this.

On Wed, Oct 4, 2017 at 10:56 AM, John Nicholas <notifications@github.com> wrote:
installed the generator and templates ... then got this

Are you sure you want to install "mix_generator-0.1.9.ez"? [Yn] y
* creating /home/john/.mix/archives/mix_generator-0.1.9
john@John-Ubuntu:~/git$ mix template.hex
** (UndefinedFunctionError) function Hex.API.Package.search/1 is undefined or private. Did you mean one of:

      * search/2

    (hex) Hex.API.Package.search("gen_template")
    lib/mix/tasks/template.hex.ex:15: Mix.Tasks.Template.Hex.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2

**Comment by MrTortoise** [comment]
youll have to forgive me i cant figure out how

**Comment by pragdave** [comment]
OK, I pushed version 0.1.14-experimental to hex.
mix archive.install hex mix_templates

On Fri, Oct 6, 2017 at 5:33 PM, John Nicholas <notifications@github.com> wrote:
youll have to forgive me i cant figure out how

**Comment by MrTortoise** [comment]
Thanks looks like that works!
